/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroCarousel: typeof import('./src/components/Hero-Carousel.vue')['default']
    HeroServices: typeof import('./src/components/Hero-Services.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Process: typeof import('./src/components/Process.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Testimonials: typeof import('./src/components/Testimonials.vue')['default']
  }
}
